"""
Graphene — Pydantic Data Models

All data shapes used across the Graphene system. These models enforce
validation on every data boundary: CSV→Python, Python→Neo4j, API→Frontend.
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class TxnType(str, Enum):
    """Transaction type enumeration matching Indian banking channels."""
    NEFT = "NEFT"
    RTGS = "RTGS"
    IMPS = "IMPS"
    UPI = "UPI"
    INTERNAL = "INTERNAL"


class Channel(str, Enum):
    """Transaction channel enumeration."""
    MOBILE = "MOBILE"
    NETBANKING = "NETBANKING"
    BRANCH = "BRANCH"
    ATM = "ATM"
    API = "API"


class TxnStatus(str, Enum):
    """Transaction status enumeration."""
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"


class AccountType(str, Enum):
    """Bank account type enumeration."""
    SAVINGS = "SAVINGS"
    CURRENT = "CURRENT"
    SALARY = "SALARY"
    DORMANT = "DORMANT"
    SHELL = "SHELL"


class CustomerCategory(str, Enum):
    """Customer category enumeration."""
    INDIVIDUAL = "INDIVIDUAL"
    BUSINESS = "BUSINESS"
    STUDENT = "STUDENT"
    RETIRED = "RETIRED"


class KYCStatus(str, Enum):
    """KYC verification status."""
    VERIFIED = "VERIFIED"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"


class FraudType(str, Enum):
    """Known AML fraud pattern types detected by Graphene."""
    CIRCULAR_ROUND_TRIP = "CIRCULAR_ROUND_TRIP"
    LAYERING = "LAYERING"
    STRUCTURING = "STRUCTURING"
    DORMANT_ACTIVATION = "DORMANT_ACTIVATION"
    PROFILE_MISMATCH = "PROFILE_MISMATCH"


class RiskTier(str, Enum):
    """Risk tier classification for accounts."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    """Alert lifecycle status."""
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    DISMISSED = "DISMISSED"
    ESCALATED = "ESCALATED"


class Transaction(BaseModel):
    """A single banking transaction record."""
    txn_id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime
    sender_account: str
    receiver_account: str
    amount: float = Field(ge=100, le=50_000_000)
    txn_type: TxnType
    channel: Channel
    status: TxnStatus = TxnStatus.SUCCESS
    description: str = ""
    is_fraud: bool = False
    fraud_type: Optional[str] = None

    @field_validator("sender_account", "receiver_account")
    @classmethod
    def validate_account_format(cls, v: str) -> str:
        """Ensure account IDs follow the ACC + 10-digit format."""
        if not v.startswith("ACC") or len(v) != 13:
            raise ValueError(
                f"Account ID must be 'ACC' + 10 digits, got: {v}"
            )
        return v


class Account(BaseModel):
    """A bank account node in the transaction graph."""
    account_id: str
    account_type: AccountType
    customer_name: str
    customer_category: CustomerCategory
    branch_code: str
    kyc_status: KYCStatus = KYCStatus.VERIFIED
    account_age_days: int = Field(ge=0)
    risk_score: float = Field(default=0.0, ge=0.0, le=1.0)
    is_flagged: bool = False

    @field_validator("account_id")
    @classmethod
    def validate_account_id(cls, v: str) -> str:
        """Ensure account IDs follow the ACC + 10-digit format."""
        if not v.startswith("ACC") or len(v) != 13:
            raise ValueError(
                f"Account ID must be 'ACC' + 10 digits, got: {v}"
            )
        return v


class Alert(BaseModel):
    """A fraud alert generated by the risk scoring engine."""
    alert_id: str = Field(default_factory=lambda: str(uuid4()))
    account_id: str
    risk_score: float = Field(ge=0.0, le=100.0)
    risk_tier: RiskTier
    triggered_patterns: list[str] = Field(default_factory=list)
    recommendation: str = ""
    evidence_summary: str = ""
    created_at: datetime = Field(default_factory=datetime.now)
    status: AlertStatus = AlertStatus.OPEN
    analyst_note: Optional[str] = None

    @field_validator("risk_tier", mode="before")
    @classmethod
    def compute_tier(cls, v: str, info) -> str:
        """Auto-compute tier from risk_score if not explicitly set."""
        return v


class SHAPExplanation(BaseModel):
    """SHAP explanation for a single model prediction."""
    account_id: str
    model: str
    fraud_probability: float
    explanation: list[dict] = Field(default_factory=list)


class FundPath(BaseModel):
    """A traced fund flow path between two accounts."""
    source_account: str
    destination_account: str
    path_length: int
    total_amount: float
    intermediate_accounts: list[str] = Field(default_factory=list)
    transactions: list[dict] = Field(default_factory=list)


class GraphData(BaseModel):
    """Cytoscape.js-ready graph data for frontend rendering."""
    nodes: list[dict] = Field(default_factory=list)
    edges: list[dict] = Field(default_factory=list)
